version: '3.6'

services:

  postgres:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_DB=nlw-feedget
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

volumes:
  db_data: